apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-board
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-board
  template:
    metadata:
      labels:
        app: fin-board
    spec:
      containers:
        - name: fin-board
          image: vishal28d/fin-board:latest
          ports:
            - containerPort: 80
